/**
 * @file validateRequest.js
 * @description Middleware that processes the results of validations performed with express-validator.
 */

const { validationResult } = require("express-validator");

/**
 * Middleware to validate the results of express-validator rules.
 *
 * If validation errors exist:
 * - Returns an **HTTP 400 Bad Request** with a JSON object containing:
 *   - `message`: general description of the error.
 *   - `errors`: detailed list of errors generated by the rules.
 *
 * If no errors exist:
 * - Continues to the next middleware or controller.
 *
 * @function
 * @param {import("express").Request} req HTTP request object.
 * @param {import("express").Response} res HTTP response object.
 * @param {import("express").NextFunction} next Function to pass control to the next middleware.
 * @returns {void}
 */

const validateRequest = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({
      message: "Error de validación",
      errors: errors.array()
    });
  }
  next();
};

module.exports = validateRequest;